apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keda-rabbitmq-secret.yaml
  - serverless-health-trigger-auth.yaml
  - serverless-health-scaledjob.yaml
  - serverless-health-init-job.yaml