apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-trigger-auth
  namespace: finance-tracker
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: host