from __future__ import annotations

from datetime import date, datetime
from typing import Any, Optional, Protocol
from uuid import UUID

from app.domain.entities import BankConnection


class IBankConnectionRepository(Protocol):
    async def save(self, connection: BankConnection) -> BankConnection: ...
    async def get_by_id(self, connection_id: UUID) -> Optional[BankConnection]: ...
    async def get_by_uid(self, bank_account_uid: str) -> Optional[BankConnection]: ...
    async def list_by_account(self, account_id: int) -> list[BankConnection]: ...
    async def update_status(self, connection_id: UUID, status: str) -> None: ...
    async def update_last_synced(self, connection_id: UUID, synced_at: datetime) -> None: ...


class IPendingAuthorizationRepository(Protocol):
    async def save(self, state: str, account_id: int, user_id: int, expires_at: datetime) -> None: ...
    async def pop(self, state: str) -> Optional[tuple[int, int]]:
        """Remove and return (account_id, user_id) for state, or None."""
        ...
    async def cleanup_expired(self) -> int:
        """Delete expired entries, return count deleted."""
        ...


class IAccountProjection(Protocol):
    async def get_account_name(self, account_id: int) -> Optional[str]: ...
    async def upsert(self, account_id: int, user_id: int, account_name: str) -> None: ...


class IBankingApiClient(Protocol):
    def get_available_banks(self, country: str = "DK") -> list[dict[str, Any]]: ...
    def start_authorization(self, bank_name: str, country: str = "DK") -> dict[str, str]: ...
    def create_session(self, auth_code: str) -> dict[str, Any]: ...
    def delete_session(self, session_id: str) -> None: ...
    def get_transactions(
        self,
        account_uid: str,
        date_from: Optional[str] = None,
    ) -> tuple[list[Any], int]: ...


class ITransactionImporter(Protocol):
    def bulk_import(
        self,
        user_id: int,
        items: list[Any],
        skip_duplicates: bool = True,
    ) -> Any: ...
