FROM node:20-alpine AS build

WORKDIR /app

COPY services/frontend/package*.json ./

RUN npm install

COPY services/frontend/ ./

RUN npm run build


FROM nginx:1.27-alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY services/frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]