from pydantic import ValidationError, EmailStr
import pytest
import re
from pydantic import ValidationError
from backend.shared.schemas.user import UserBase, UserCreate


# USER_BVA constants are available (min=3, max=20)

VALID_EMAIL = "test@example.com"

# Min Length (N-1) - INVALID (2 chars)
def test_base_username_min_length_below_boundary_invalid():
    # ACT & ASSERT
    with pytest.raises(ValidationError):
        UserBase(username="ab", email=VALID_EMAIL)

# Min Length (N) - VALID (3 chars)
def test_base_username_min_length_at_boundary_valid():
    username = "abc"
    user = UserBase(username=username, email=VALID_EMAIL)
    assert user.username == username

# Max Length (M) - VALID (20 chars)
def test_base_username_max_length_at_boundary_valid():
    username = "a" * 20
    user = UserBase(username=username, email=VALID_EMAIL)
    assert len(user.username) == 20

# Max Length (M+1) - INVALID (21 chars)
def test_base_username_max_length_above_boundary_invalid():
    # ACT & ASSERT
    with pytest.raises(ValidationError):
        UserBase(username="a" * 21, email=VALID_EMAIL)


# Username Format Tests

# Format - Invalid Characters (e.g., spaces) - INVALID
def test_base_username_format_invalid_characters():
    # ACT & ASSERT (Contains space, violating r"^\w+$")
    with pytest.raises(ValueError, match="Username må kun indeholde bogstaver, tal og underscore"):
        UserBase(username="user name", email=VALID_EMAIL)

# Format - Valid Characters (Alphanumeric + Underscore) - VALID
def test_base_username_format_valid_characters():
    username = "user_name_123"
    user = UserBase(username=username, email=VALID_EMAIL)
    assert user.username == username

# Emptiness - Whitespace Only (UGYLDIG)
def test_base_username_whitespace_only_invalid():
    # ACT & ASSERT (It will fail the FORMAT check first because space is not \w)
    with pytest.raises(ValueError, match="Username må kun indeholde bogstaver, tal og underscore"):
        UserBase(username="   ", email=VALID_EMAIL)

#FIXME:
# Emptiness - Leading/Trailing Whitespace (Valid and stripped) 
#def test_base_username_whitespace_stripped_valid():
    #input_username = " username "
    #expected_username = "username"
    #user = UserBase(username=input_username, email=VALID_EMAIL)
    #assert user.username == expected_username

# Email Validation Tests

# Email - Invalid Format (Missing @ or domain) - INVALID
def test_base_email_format_invalid():
    # ACT & ASSERT (Pydantic's EmailStr handles this)
    with pytest.raises(ValidationError):
        UserBase(username="testuser", email="invalid-email")

# Email - Normalization to Lowercase
def test_base_email_normalization_valid():
    input_email = "Test.User@Example.com"
    expected_email = "test.user@example.com"
    user = UserBase(username="testuser", email=input_email)
    # The validate_email_format validator should normalize this
    assert user.email == expected_email


#  UserCreate Schema Tests

# Helper data for valid creation
VALID_USERNAME = "validuser"
VALID_EMAIL = "valid@example.com"
MIN_PASSWORD_LENGTH = 8 # Assuming 8 from USER_BVA

# Required Field - Missing Password - INVALID
def test_create_missing_password_invalid():
    # ACT & ASSERT (Password is required in UserCreate)
    with pytest.raises(ValidationError) as excinfo:
        UserCreate(username=VALID_USERNAME, email=VALID_EMAIL)
    
    assert "password" in str(excinfo.value)


# 12. Password Min Length (N-1) - INVALID (7 chars)
def test_create_password_min_length_below_boundary_invalid():
    # ARRANGE: Use a password that is too short (7 characters)
    password = "a" * (MIN_PASSWORD_LENGTH - 1) 

    # ACT & ASSERT: Expect the standard Pydantic ValidationError
    with pytest.raises(ValidationError) as excinfo:
        UserCreate(
            username=VALID_USERNAME, 
            email=VALID_EMAIL, 
            password=password
        )
    
    # Assert that the error is for the 'password' field 
    # and contains the specific message generated by the min_length constraint.
    assert 'password' in str(excinfo.value)
    # Asserting for the exact phrase Pydantic V2 gives you:
    assert f"String should have at least {MIN_PASSWORD_LENGTH} characters" in str(excinfo.value)

# Password Min Length (N) - VALID (8 chars)
def test_create_password_min_length_at_boundary_valid():
    password = "a" * MIN_PASSWORD_LENGTH
    user = UserCreate(username=VALID_USERNAME, email=VALID_EMAIL, password=password)
    assert len(user.password) == MIN_PASSWORD_LENGTH

# Inheritance Check - Username Max Length (Confirming UserBase logic is inherited)
def test_create_inheritance_username_max_length_invalid():
    # ACT & ASSERT (Confirms max_length=20 constraint is active in UserCreate)
    with pytest.raises(ValidationError):
        UserCreate(
            username="a" * 21,  # INVALID length
            email=VALID_EMAIL,
            password="a" * MIN_PASSWORD_LENGTH
        )